### PR TITLE
This closes #231, closes #230, closes #228, closes #226, closes #218,…

### LINKED ISSUE #144: Create Not found and Access denied pages
Create "404 - Not found" and "403 - Access denied" pages and configure Drupal to redirect to them in given case. 

captura de pantalla 2017-04-02 a las 12 37 03
captura de pantalla 2017-04-02 a las 12 37 17

### LINKED ISSUE #218: Add styles to the attendees pager
See https://dev.drupalcamp.es/attendees/list?page=1

Further details at https://github.com/AsociacionDrupalES/DrupalCampSpain/issues/175#issuecomment-293209474

### LINKED ISSUE #226: Hamburger link does not work on page nodes when authenticated
Steps to reproduce:

1. Log in at https://2017.drupalcamp.es.
2. Open https://2017.drupalcamp.es/es/business-day.
3. Click on the hamburguer.

Expected: the menu expands.
Actual: nothing happens.

### LINKED ISSUE #228: Wrong indentation of lists
See the list in the following screenshot taken from https://2017.drupalcamp.es/es/taller-de-introduccion-a-drupal:

image

### LINKED ISSUE #230: Change Frontpage Page Title
Currently the page title is 'Home'. I think that could be improved for Search Engine Optimization.

### LINKED ISSUE #231: Change header image to full width.
Looks naff having the image cut off on big screens.

### PR DESCRIPTION
**Pull request by nuez**
… closes #221, closes #144

### CODE REVIEW

**Comment by nuez** [comment]
Also fixes the lines on the top of the main menu, that were not as high as the menu button. (55px instead of 60)

File: web/themes/dcamp_2017_theme/scripts/main.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
   Drupal.behaviors.dcamp2017ThemeBehaviors = {
     attach: function (context, settings) {
-      $('.main-menu__trigger').click(function () {
+      $('.main-menu__trigger').once().click(function () {
```
Comment (juampynr) [inline web/themes/dcamp_2017_theme/scripts/main.js]: :+1:
